// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpkwpfrsruekczjmxubg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwa3dwZnJzcnVla2N6am14dWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDYxNDksImV4cCI6MjA3MTA4MjE0OX0.uvWjOjUcWcSrnbh_5kZ1IQd7rccTUpJd3fSc58mTr_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});